apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-deployment
  labels: 
    app: wordpress-mirantis
spec:
  selector:
    matchLabels:
      app: wordpress-mirantis
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: wordpress-mirantis
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-app
        ports:
        - containerPort: 80
          name: wordpress-app
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}

